export const commandItems = [
  { title: "Overview", href: "/dashboard" },
  { title: "Human Twin", href: "/dashboard/human-twin" },
  { title: "AI Companion", href: "/dashboard/ai-companion" },
  { title: "Assessment", href: "/dashboard/assessment" },
  { title: "Identity", href: "/dashboard/identity" },
  { title: "Personality", href: "/dashboard/personality" },
  { title: "Goals", href: "/dashboard/goals" },
  { title: "Habits", href: "/dashboard/habits" },
  { title: "Journal", href: "/dashboard/journal" },
  { title: "Calendar", href: "/dashboard/calendar" },
  { title: "Wellness Hub", href: "/dashboard/wellness" },
  { title: "Life Domains", href: "/dashboard/life-domains" },
  { title: "Impact", href: "/dashboard/impact" },
  { title: "Achievements", href: "/dashboard/achievements" },
  { title: "Leaderboard", href: "/dashboard/leaderboard" },
  { title: "Community", href: "/dashboard/community" },
  { title: "Messages", href: "/dashboard/messages" },
  { title: "Trusted Circle", href: "/dashboard/trusted-circle" },
  { title: "Therapy", href: "/dashboard/therapy" },
  { title: "Knowledge Base", href: "/dashboard/knowledge-base" },
  { title: "Reports", href: "/dashboard/reports" },
  { title: "Growth Journey", href: "/dashboard/growth-journey" },
  { title: "Wellness Intelligence", href: "/dashboard/wellness-intelligence" },
  { title: "Settings", href: "/dashboard/settings" },
];
